---
title: "merge_idx_meta_genomecov"
author: "Douglas Yu"
date: "10/02/2018"
output: html_document
---

```{r}
# rm(list=ls())
library(tidyverse)
library(readxl)
library(lubridate)
library(knitr)
```


```{r load PlatesAB}
setwd("~/Dropbox/Working_docs/Roslin_Greenland/2016/bulk_samples/PlatesAB_EI_20160512/")

idx_meta_genomecov_AB <- read_delim("idx_meta_genomecov_PlatesAB_20180211.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)

idx_meta_genomecov_AB <- idx_meta_genomecov_AB %>% dplyr::select(Date:mitogenome, mapped_reads, mapped_reads_COI_corr, mapped_reads_COI_lysis_corr, sum_coverage, mean_coverage, stddev, coefvar, samtools_filter, mt_length, lysis_buffer_orig_total_ul, lysis_buffer_purified_ul, lysis_buffer_proportion, Lepidoptera_Bombycidae_Bombyx_mori_10ng_COI, Coleoptera_Mordellidae_20ng_COI, Coleoptera_Elateridae_40ng_COI, elaterid_mordellid_sum, COI_corr, Concentration_ng_per_ul, Sample_volume_ul, x.260_280_ratio, sample, ArcDyn_Plate_name, EI_Plate_name, well, Sample_alias, TGAC_barcode, pathname, pathname_genomecov, Full_name_of_the_sample)

idx_meta_genomecov_AB$COI_corr_components <- "elaterid_mordellid_sum"

idx_meta_genomecov_AB <- idx_meta_genomecov_AB %>% dplyr::select(Date:Coleoptera_Elateridae_40ng_COI, COI_corr_components, COI_corr:Full_name_of_the_sample)

idx_meta_genomecov_AB$EI_RUN <- "idx_meta_genomecov_AB"
```


```{r load PlatesA2B2}
setwd("~/Dropbox/Working_docs/Roslin_Greenland/2017/bulk_samples/PlatesA2B2")

idx_meta_genomecov_A2B2 <- read_delim("idx_meta_genomecov_PlatesA2B2_20180211.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)

# names(idx_meta_genomecov_A2B2)

idx_meta_genomecov_A2B2 <- idx_meta_genomecov_A2B2 %>% dplyr::select(Date:mitogenome, mapped_reads, mapped_reads_COI_corr, mapped_reads_COI_lysis_corr, sum_coverage, mean_coverage, stddev, coefvar, samtools_filter, mt_length, lysis_buffer_orig_total_ul, lysis_buffer_purified_ul, lysis_buffer_proportion, Lepidoptera_Bombycidae_Bombyx_mori_10ng_COI, Coleoptera_Mordellidae_20ng_COI, Coleoptera_Elateridae_40ng_COI, elaterid_mordellid_sum, COI_corr, Concentration_ng_per_ul, Sample_volume_ul, x.260_280_ratio, sample, ArcDyn_Plate_name, EI_Plate_name, well, Sample_alias, TGAC_barcode, pathname, pathname_genomecov, Full_name_of_the_sample)

idx_meta_genomecov_A2B2$COI_corr_components <- "elaterid_mordellid_sum"

idx_meta_genomecov_A2B2 <- idx_meta_genomecov_A2B2 %>% dplyr::select(Date:Coleoptera_Elateridae_40ng_COI, COI_corr_components, COI_corr:Full_name_of_the_sample)

idx_meta_genomecov_A2B2$EI_RUN <- "idx_meta_genomecov_A2B2"
```


```{r load PlatesEF}
setwd("~/Dropbox/Working_docs/Roslin_Greenland/2017/bulk_samples/PlatesEF")

idx_meta_genomecov_EF <- read_delim("idx_meta_genomecov_PlatesEF_20180211.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)

# names(idx_meta_genomecov_EF)

idx_meta_genomecov_EF <- idx_meta_genomecov_EF %>% dplyr::select(Date:mitogenome, mapped_reads, mapped_reads_COI_corr, mapped_reads_COI_lysis_corr, sum_coverage, mean_coverage, stddev, coefvar, samtools_filter, mt_length, lysis_buffer_orig_total_ul, lysis_buffer_purified_ul, lysis_buffer_proportion, Lepidoptera_Bombycidae_Bombyx_mori_10ng_COI, Coleoptera_Mordellidae_20ng_COI, Coleoptera_Elateridae_40ng_COI, bombycid_mordellid_sum, COI_corr, Concentration_ng_per_ul, Sample_volume_ul, x.260_280_ratio, sample, ArcDyn_Plate_name, EI_Plate_name, well, Sample_alias, pathname, pathname_genomecov, Full_name_of_the_sample)

idx_meta_genomecov_EF$TGAC_barcode <- "NA"  # not in the sample metadata

idx_meta_genomecov_EF$COI_corr_components <- "bombycid_mordellid_sum"

idx_meta_genomecov_EF$EI_Plate_name <- as.character(idx_meta_genomecov_EF$EI_Plate_name)

idx_meta_genomecov_EF <- idx_meta_genomecov_EF %>% dplyr::select(Date:Coleoptera_Elateridae_40ng_COI, COI_corr_components, COI_corr:Sample_alias, TGAC_barcode, pathname:Full_name_of_the_sample)

idx_meta_genomecov_EF$EI_RUN <- "idx_meta_genomecov_EF"
```


```{r load PlatesGH}
setwd("~/Dropbox/Working_docs/Roslin_Greenland/2017/bulk_samples/PlatesGH")

idx_meta_genomecov_GH <- read_delim("idx_meta_genomecov_PlatesGH_20180211.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)

idx_meta_genomecov_GH <- idx_meta_genomecov_GH %>% dplyr::rename(Concentration_ng_per_ul="Concentration_ng_ul")
idx_meta_genomecov_GH <- idx_meta_genomecov_GH %>% dplyr::rename(ArcDyn_Plate_name="Plate")
idx_meta_genomecov_GH <- idx_meta_genomecov_GH %>% dplyr::rename(TGAC_barcode="EI_sample_name")

# qty_loaded_uL # is in this dataset and probably should add to all samplemetadata files

# names(idx_meta_genomecov_GH)

idx_meta_genomecov_GH <- idx_meta_genomecov_GH %>% dplyr::select(Date, Plot:mitogenome, mapped_reads, mapped_reads_COI_corr, mapped_reads_COI_lysis_corr, sum_coverage, mean_coverage, stddev, coefvar, samtools_filter, mt_length, lysis_buffer_orig_total_ul, lysis_buffer_purified_ul, lysis_buffer_proportion, Lepidoptera_Bombycidae_Bombyx_mori_10ng_COI, Coleoptera_Mordellidae_20ng_COI, Coleoptera_Elateridae_40ng_COI, elaterid_mordellid_sum, COI_corr, Concentration_ng_per_ul, Sample_volume_ul, x.260_280_ratio, sample, ArcDyn_Plate_name, well, Sample_alias, TGAC_barcode, pathname, pathname_genomecov, Full_name_of_the_sample)

idx_meta_genomecov_GH$EI_Plate_name <- "NA"  # not in the sample metadata

idx_meta_genomecov_GH$COI_corr_components <- "elaterid_mordellid_sum"

idx_meta_genomecov_GH <- idx_meta_genomecov_GH %>% dplyr::select(Date:Coleoptera_Elateridae_40ng_COI, COI_corr_components, COI_corr:ArcDyn_Plate_name, EI_Plate_name, well:Full_name_of_the_sample)

idx_meta_genomecov_GH$EI_RUN <- "idx_meta_genomecov_GH"
```


```{r}
names_AB <- names(idx_meta_genomecov_AB)
names_A2B2 <- names(idx_meta_genomecov_A2B2)
names_EF <- names(idx_meta_genomecov_EF)
names_GH <- names(idx_meta_genomecov_GH)
      
identical(names_AB, names_A2B2) # TRUE
identical(names_AB, names_EF) # TRUE
identical(names_AB, names_GH) # TRUE

# bind rows together
idx_meta_genomecov_ABA2B2EFGH <- bind_rows(idx_meta_genomecov_AB, idx_meta_genomecov_A2B2, idx_meta_genomecov_EF, idx_meta_genomecov_GH)

# put EI_RUN column first
idx_meta_genomecov_ABA2B2EFGH <- idx_meta_genomecov_ABA2B2EFGH %>% dplyr::select(EI_RUN, Date:Full_name_of_the_sample)

# confirm 157 mitogenomes
idx_meta_genomecov_ABA2B2EFGH %>% distinct(mitogenome) %>% count()  # 157: number of distinct values of mitogenome (160 total mitogenomes - the 3 COI spikes = 157)

# view names
names(idx_meta_genomecov_ABA2B2EFGH)
#  [1] "EI_RUN"                                      "Date"                                       
#  [3] "Plot"                                        "Trap"                                       
#  [5] "Week"                                        "mitogenome"                                 
#  [7] "mapped_reads"                                "mapped_reads_COI_corr"                      
#  [9] "mapped_reads_COI_lysis_corr"                 "sum_coverage"                               
# [11] "mean_coverage"                               "stddev"                                     
# [13] "coefvar"                                     "samtools_filter"                            
# [15] "mt_length"                                   "lysis_buffer_orig_total_ul"                 
# [17] "lysis_buffer_purified_ul"                    "lysis_buffer_proportion"                    
# [19] "Lepidoptera_Bombycidae_Bombyx_mori_10ng_COI" "Coleoptera_Mordellidae_20ng_COI"            
# [21] "Coleoptera_Elateridae_40ng_COI"              "COI_corr_components"                        
# [23] "COI_corr"                                    "Concentration_ng_per_ul"                    
# [25] "Sample_volume_ul"                            "x.260_280_ratio"                            
# [27] "sample"                                      "ArcDyn_Plate_name"                          
# [29] "EI_Plate_name"                               "well"                                       
# [31] "Sample_alias"                                "TGAC_barcode"                               
# [33] "pathname"                                    "pathname_genomecov"                         
# [35] "Full_name_of_the_sample"            
```


```{r make wide table}
# create variable from Date, Trap(ABC), and EI_RUN:  e.g. Date_1997_08_04_TrapA_AB
# stringr::str_pad(x, width = 2, side = "left", pad = "0")  # to ensure that the date always has two digits, e.g. 07.
# stringr::str_replace(idx_meta_genomecov_ABA2B2EFGH$EI_RUN, "idx_meta_genomecov_", "") # to extract AB, A2B2, EF, GH from EI_RUN
idx_meta_genomecov_ABA2B2EFGH$DateTrapEIRUN <- str_c("Date", year(idx_meta_genomecov_ABA2B2EFGH$Date), str_pad(month(idx_meta_genomecov_ABA2B2EFGH$Date), 2, side = "left", pad = "0"), str_pad(day(idx_meta_genomecov_ABA2B2EFGH$Date), 2, side = "left", pad = "0"), idx_meta_genomecov_ABA2B2EFGH$Trap, str_replace(idx_meta_genomecov_ABA2B2EFGH$EI_RUN, "idx_meta_genomecov_", ""), sep = "_")


# Make wide table for visualisation (left to right should follow temporal order (DateTrapEIRUN))
idx_meta_genomecov_ABA2B2EFGH_wide <- idx_meta_genomecov_ABA2B2EFGH %>% dplyr::select(DateTrapEIRUN, mitogenome, mapped_reads_COI_lysis_corr) %>% dplyr::arrange(DateTrapEIRUN) %>% tidyr::spread(DateTrapEIRUN, mapped_reads_COI_lysis_corr) %>% dplyr::arrange(mitogenome)

```


```{r write tables, eval=FALSE}
# idx_meta-genomecov long table for Otso, 110057 rows, 36 columns
setwd("~/Dropbox/Working_docs/Roslin_Greenland/2017/bulk_samples/PlatesABA2B2EFGH")
write_tsv(idx_meta_genomecov_ABA2B2EFGH, "idx_meta_genomecov_ABA2B2EFGH_20180211.txt")

# idx_meta-genomecov wide table for visualisation:  157 rows, 702 columns
write_tsv(idx_meta_genomecov_ABA2B2EFGH_wide, "idx_meta_genomecov_ABA2B2EFGH_wide_20180211.txt")
```


